Working on contact form section
mauriciomonta/web_portfolio pull request #7
Opened 2021-11-02 14:39 UTC by mauriciomonta

We working on the contact form section with my code partner.

2021-11-02 19:19 UTC, alonsofl requested changes
Hi @mauriciomonta and @Eckybrazzz,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- Good form implementation :heavy_check_mark:
- Your design looks great! :fire:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- I would suggest that the next time you submit a PR it should contain the added/changed lines in order to get a proper review. Remember that most of the time you will be working in teams and they will want to see all the introduced changes in the PR.
[Reviewed branch](https://github.com/mauriciomonta/web_portfolio/blob/contact-form/index.html)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-02 19:19 UTC, alonsofl commented on index.html
>        </form>
- [ ] You have done a good job implementing the form but one of the project requirements is to make all the input fields `required` so the form could not be submitted if one of the fields it's empty. I would suggest fixing this issue to meet the project requirements :raised_hands:

![image](https://user-images.githubusercontent.com/81522435/139929789-ebe905aa-95b6-46d5-9a94-fee3889e8ea5.png)

- [ ] I think you have missed the footer section with the social icons. I would suggest adding the required section to match the Figma design as required :wink:
**Don't forget the section background** :pushpin:

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/139930128-347f4bd7-0b27-488e-8d5f-d4f761345526.png)

2021-11-04 15:07 UTC, VanessaAoki requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @mauriciomonta, 

Great work on making the changes requested by a previous reviewer, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
 - [ ] There are still some inputs in your form that are not `required`. According to the previous code reviewer and the project's requirements, the user should not be able to submit the form if one or more fields are empty.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 - [ ] [OPTIONAL]: Right now your live demo link is broken. You should consider fixing the deployment or removing the link, for now.

![really close](https://c.tenor.com/fuKjtbt7b4EAAAAd/really-really-close-bill-murray.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 15:17 UTC, VanessaAoki approved these changes
# STATUS: APPROVED 🟢 
Hi @mauriciomonta, 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 
Congratulations! 🎉 

<img alt="approved" src="https://64.media.tumblr.com/87e0b6469c957bf896cdec1cab646acf/tumblr_inline_pk1bdakCCp1rpcr9a_500.gif">

## Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 16:01 UTC, closed without merging