Working on desktop version
mauriciomonta/web_portfolio pull request #9
Opened 2021-11-04 16:06 UTC by mauriciomonta

Vectors were added and tried to keep the template style.

2021-11-04 17:27 UTC, alonsofl requested changes
Hi @mauriciomonta,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- Linters are working properly :heavy_check_mark:
- Good use of media queries :heavy_check_mark:
- The animations and the design look great! :fire:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 17:27 UTC, alonsofl commented on style.css
> +@media screen and (max-width: 992px) {
- [OPTIONAL] You have done a great job implementing the media query for the desktop version, but the issue here is that your portfolio is supposed to be a mobile-first design, this means that the mobile design is the "main" design/query and the larger devices are supposed to be in media queries. In your case, you are using the `max-width` property because you are applying the "mobile version" after that breakpoint. I would suggest using the `min-width: 992px` property, to make your design mobile-first :pushpin: :wink:

2021-11-04 17:27 UTC, alonsofl commented on index.html
> +          <p class="paragraph">
- [ ] I would suggest updating the text size for the desktop version because it's the same as the mobile version and it could be too small for large devices :raised_hands:
![image](https://user-images.githubusercontent.com/81522435/140387103-a3e87979-304b-41b3-a363-34fd38ec3af8.png)


  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/140386890-98d76d68-8e6d-4edf-a9e9-861ad5e939fd.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/140387047-669dd562-8692-41fa-ace0-d18685d5d4e7.png)

2021-11-04 17:27 UTC, alonsofl commented on style.css
>  .title {
- [ ] Also here, I think you could add some `font-size` to match the Figma design, also the desktop version does not have the `<br>` tag :wink:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/140387585-aab79f8b-2fec-4811-9f72-8c5b2d2e902b.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/140387649-579e429d-5f99-42cd-9051-34e6952a8deb.png)

2021-11-04 17:27 UTC, alonsofl commented on index.html
>        <h3 class="title">About me</h3>
- [ ] I think it could be a good idea to update this desktop version `font-size` here too for a better user experience :wink:

  ![image](https://user-images.githubusercontent.com/81522435/140388247-de5f5789-ead4-42f6-ae57-728ff7a38e17.png)

2021-11-04 17:27 UTC, alonsofl commented on index.html
> +          <li><a href="#">Contact</a></li>
- [ ] I think it might be a good idea to add the values of the `href` attributes to link your sections. This will help the users navigate in your portfolio :smiley:

2021-11-05 05:53 UTC, D4nielJ approved these changes
## Hello @mauriciomonta, 

Your project is complete!  There is nothing else to say other than... wooooooowww!! :shipit: 
Congratulations! 🎉

![](https://c.tenor.com/tYNRpHAQGmsAAAAC/cheering-hurray.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-05 06:02 UTC, merged